/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
var styles = [".media[_ngcontent-%COMP%] {\r\n  margin-bottom: 30px;\r\n}"];
export { styles as styles };
//# sourceMappingURL=github-followers.component.css.shim.ngstyle.js.map